In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
type(a)

numpy.ndarray

In [11]:
a.shape

(3,)

In [5]:
a.itemsize

8

In [6]:
a.size

3

In [7]:
a.nbytes

24

#### accessing specific. elements, rows, columns etc.

In [8]:
b = np.array([[1,2,3,4,5],[6,7,8,9,0]])

In [9]:
print(b)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [16]:
# get a specific element [r,c] ------ extracting 9

b[1,3]

9

In [17]:
# get a row
b[0,:]

array([1, 2, 3, 4, 5])

In [18]:
# get a column
b[:,2]

array([3, 8])

In [20]:
# little more complex ----- get every alternale elemnt from the first row----format-[startindex:endindex:stepsize]
b[0,0::2]

array([1, 3, 5])

In [28]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
c.shape

(2, 2, 2)

In [31]:
c[:,1,:]

array([[3, 4],
       [7, 8]])

#### initilizing different types of array

In [39]:
# all 0s array
np.zeros((2,3,4),dtype = float)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [42]:
# all 1s array
np.ones((2,3,4),dtype = 'int16')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [45]:
np.full((2,3,2),15,dtype =  'float32')

array([[[15., 15.],
        [15., 15.],
        [15., 15.]],

       [[15., 15.],
        [15., 15.],
        [15., 15.]]], dtype=float32)

In [49]:
# full like method detects the shape of an existing array
np.full_like(c,4,dtype = int)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [52]:
# array of random numbers 
np.random.rand(3,2)

array([[0.39644995, 0.26309488],
       [0.85780001, 0.57699876],
       [0.02983645, 0.28732618]])

In [57]:
np.random.random_sample(c.shape)

array([[[0.00939492, 0.13406353],
        [0.54968469, 0.81404049]],

       [[0.69480042, 0.52301647],
        [0.18098651, 0.73724916]]])

In [62]:
np.random.randint(1,10, size = (2,3))

array([[7, 2, 3],
       [7, 6, 7]])

In [63]:
# the identity matrix 
np.identity(3,dtype= 'float32')

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [69]:
arr1  = np.array([[1,2,3]])
arr2 = np.repeat(arr1,4,axis =0)
print(arr2)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [80]:
# be careful while copying the array
arr3 = arr1.copy()

In [71]:
arr1.shape

(1, 3)

In [81]:
arr3[:,2]= 12

In [82]:
print(arr1)
print(arr3)

[[ 1  2 25]]
[[ 1  2 12]]


#### Linear Algebra

In [84]:
x = np.ones((2,3))
y = np.full((3,2),2)
print(x)
print(y)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [87]:
np.matmul(x,y)

array([[6., 6.],
       [6., 6.]])

In [91]:
stats = np.array([[1,2,3],[6,7,8]],)
print(stats)

[[1 2 3]
 [6 7 8]]


In [94]:
np.max(stats,axis =1)

array([3, 8])

In [95]:
np.min(stats,axis =0)

array([1, 2, 3])

In [97]:
np.sum(stats,axis =0)

array([ 7,  9, 11])